### ISSUE TITLE
Link to the specimen page from the home page

### ISSUE THREAD

**Issue by waldyrious** [rse/typopro#3]
Perhaps it's intentional, but I noticed that http://typopro.org/ doesn't contain a link to http://typopro.org/specimen/.

**Comment by rse** [comment]
Why do you think that there is no such link? You can click on the large image and you can click on the bold text "773 individual fonts of 109 font families". Both are links to exactly this URL.

**Comment by waldyrious** [comment]
Ah, I see. I think it's fair to say that it isn't expectable that the image would link to the specimen page (usually when images are clickable, they either link to the full resolution version, or show a lightbox). As for the bold text, well, it is styled precisely as bold text: no different color, no underline -- which are the classical signals of a link in a web page. I would suggest making it underlined, or making it a slightly different color than the text, to provide a visual hint that it is a link.
